"""Codegen L2: domains -> patterns.h for the eBPF TC filter. No root.

Usage:
  python3 codegen.py youtube.com tiktok.com --out patterns.h
  python3 codegen.py --domains-file ../domains.txt --out patterns.h
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sni import bases_from_domains

MAX_PATTERNS = 64
MAX_PAT_LEN = 64


def render(patterns: list[str], port: int = 443) -> str:
    if len(patterns) > MAX_PATTERNS:
        raise ValueError(f"patterns {len(patterns)} > {MAX_PATTERNS}: cut the list")
    lines = [
        "/* AUTOGENERATED by codegen.py — do not edit. */",
        "#pragma once",
        "",
        f"#define BETON_NPATS {len(patterns)}",
        f"#define BETON_MAX_PAT_LEN {MAX_PAT_LEN}",
        f"#define BETON_PORT {port}",
        "",
        "struct beton_pat { __u8 len; __u8 data[BETON_MAX_PAT_LEN]; };",
        "",
        "__attribute__((unused)) static const struct beton_pat beton_pats[BETON_NPATS] = {",
    ]
    for p in patterns:
        b = p.encode("ascii")
        if len(b) > MAX_PAT_LEN:
            raise ValueError(f"pattern too long: {p}")
        init = ", ".join(str(x) for x in b)
        lines.append(f'  {{ {len(b)}, {{{init}}} }}, /* {p} */')
    lines += ["};", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("domains", nargs="*")
    ap.add_argument("--domains-file", default=None)
    ap.add_argument("--port", type=int, default=443)
    ap.add_argument("--out", default="patterns.h")
    a = ap.parse_args()
    raw = list(a.domains)
    if a.domains_file:
        with open(a.domains_file, encoding="utf-8") as f:
            raw += [l.strip() for l in f if l.strip()]
    patterns = sorted(bases_from_domains(raw))
    if not patterns:
        print("empty: no domains")
        return 2
    for p in patterns:
        try:
            p.encode("ascii")
        except UnicodeEncodeError:
            print(f"non-ascii base after normalization: {p}")
            return 2
    with open(a.out, "w", encoding="utf-8") as f:
        f.write(render(patterns, a.port))
    print(f"{len(patterns)} patterns port {a.port} -> {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
